feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
server:
  port: ${random.int[5000,9999]}
spring:
  application:
    name: auths-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #json日期格式
    time-zone: GMT+8 #北京时间 
  